### PR TITLE
Move all constants to dedicated class.

### LINKED ISSUE #23: Move all constants to dedicated class
Issue inspired from [discussion](https://github.com/Ricochet-Exchange/ricochet-keeper/pull/22#discussion_r789705568) on #22.

### PR DESCRIPTION
**Pull request by nikramakrishnan**
fixes #23

### CODE REVIEW

**Comment by nikramakrishnan** [comment]
@mikeghen ready to review 🎉

**Comment by shreyaspapi** [comment]
Tested the `distribute` , `tellor` dag working fine.

**Review by josealonso — APPROVED** [review]

**Comment by mikeghen** [comment]
@nikramakrishnan @shreyaspapi sorry this took so long to get to, this looks good, how can someone customize these variables, do they add an airflow variable for it?

**Comment by shreyaspapi** [comment]
> @nikramakrishnan @shreyaspapi sorry this took so long to get to, this looks good, how can someone customize these variables, do they add an airflow variable for it?

Oh no I think you got this PR wrong, the reason for this PR was to have all default value contents in one place. here - `dags/constants/constants.py`, Like the one we have for `distribute-schedule`.

So instead of writing - 

`SCHEDULE_INTERVAL = Variable.get("distribution-schedule-interval", "0 * * * *")`

or 

`gas_multiplier=1.1`

we can -

`SCHEDULE_INTERVAL = Variable.get("distribution-schedule-interval", ScheduleConstants.RICOCHET_DISTRIBUTE)`

or 

`gas_multiplier=PriceConstants.GAS_MULTIPLIER_DEFAULT`

and easily change the default values from `dags/constants/constants.py`

**Comment by mikeghen** [comment]
@shreyaspapi @nikramakrishnan, you can update the merge conflicts and then this can be merged

**Pull request merged**
